
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Node : Luban.BeanBase
{
    public Node(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["nodeLevel"].IsString) { throw new SerializationException(); }  NodeLevel = _buf["nodeLevel"]; }
        { if(!_buf["nodeIncome"].IsNumber) { throw new SerializationException(); }  NodeIncome = _buf["nodeIncome"]; }
        { if(!_buf["nodeCost"].IsNumber) { throw new SerializationException(); }  NodeCost = _buf["nodeCost"]; }
    }

    public static Node DeserializeNode(JSONNode _buf)
    {
        return new Node(_buf);
    }

    /// <summary>
    /// 节点id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 节点名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string NodeLevel;
    /// <summary>
    /// 节点等级
    /// </summary>
    public readonly int NodeIncome;
    /// <summary>
    /// 节点收入
    /// </summary>
    public readonly int NodeCost;
   
    public const int __ID__ = 2433570;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "nodeLevel:" + NodeLevel + ","
        + "nodeIncome:" + NodeIncome + ","
        + "nodeCost:" + NodeCost + ","
        + "}";
    }
}
}

